language: python
python:
 - "2.7"
 - "3.3"
install:
 - pip install .
 - pip install coverage
 - pip install redis
 - "if [[ $TRAVIS_PYTHON_VERSION == 2.7* ]]; then pip install pylibmc; fi"
 - "if [[ $TRAVIS_PYTHON_VERSION == 3.3* ]]; then pip install python3-memcached; fi"
script: nosetests --with-coverage --cover-package=flask_cache
services:
 - memcached
 - redis-server
